[package]
name = "fastcopy"
version = "0.1.0"
authors = ["Nicolas Koch <nioko1337@gmail.com>"]

[[bin]]
name = "main"
path = "bin/main.rs"

[dependencies]
libc = "0.2"

[dev-dependencies]
tempfile = "3"
